credentials_cfg_file = "doit_PowerOutage_Credentials.cfg"
json_file_local_location_and_name = "JSON_Outputs\PowerOutageFeeds_StatusJSON.json"
provider_uri_cfg_file = "doit_PowerOutage_ProviderURI.cfg"
sql_insert_record_county_realtime = """INSERT INTO dbo.RealTime_PowerOutagesCounty(STATE, COUNTY, OUTAGE, PROVIDER, UPDATED, CREATED) VALUES ('{state}','{county}',{outages},'{abbrev}','{date_updated}','{date_created}')"""
sql_insert_record_zip_realtime = """INSERT INTO dbo.RealTime_PowerOutagesZipcodes(ZIPCODE, PROVIDER, OUTAGE, CREATED, UPDATED) VALUES ('{area}','{abbrev}',{outages},'{date_created}','{date_updated}')"""
sql_insert_record_zip_archive = """INSERT INTO dbo.Archive_PowerOutagesZipcode(ZIPCODE, ID, PROVIDER, OUTAGE, CREATED, UPDATED, ARCHIVED) VALUES ('{area}','NULL','{abbrev}',{outages},'{date_created}','{date_updated}','{date_updated}')"""
sql_select_counties_viewforarchive = """SELECT state, county, outage, updated, percentage FROM OSPREYDB_DEV.dbo.PowerOutages_PowerOutagesViewForArchive WHERE state is not Null"""
sql_select_grouped_zipcodes = """SELECT * FROM dbo.RealTime_PowerOutagesZipcodes_Grouped"""
sql_update_customer_counts_table = """UPDATE dbo.RealTime_PowerOutagesCounty_Customers SET Customers = {cust_count} WHERE County = '{area}'"""
sql_select_zip_by_provider_abbrev_realtime = """SELECT zipcode FROM dbo.RealTime_PowerOutagesZipcodes WHERE PROVIDER = '{provider_abbrev}'"""
sql_select_by_provider_abbrev_statement_realtime = """SELECT {fields} FROM dbo.RealTime_PowerOutages{style} WHERE PROVIDER = '{provider_abbrev}'"""
sql_delete_statement = "DELETE FROM RealTime_PowerOutages{style} WHERE PROVIDER = '{provider_abbrev}'"
database_connection_string = "DSN={database_name};UID={database_user};PWD={database_password}"